# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o grafo.o dfs.o dijkstra.o bfs.o
LINKOBJ  = main.o grafo.o dfs.o dijkstra.o bfs.o
LIBS     = -L"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/lib" -L"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/include" -I"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/include" -I"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Faculdade/dev cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

grafo.o: grafo.cpp
	$(CPP) -c grafo.cpp -o grafo.o $(CXXFLAGS)

dfs.o: dfs.cpp
	$(CPP) -c dfs.cpp -o dfs.o $(CXXFLAGS)

dijkstra.o: dijkstra.cpp
	$(CPP) -c dijkstra.cpp -o dijkstra.o $(CXXFLAGS)

bfs.o: bfs.cpp
	$(CPP) -c bfs.cpp -o bfs.o $(CXXFLAGS)
